#!/usr/bin/env python3
"""Issue #57 helper: 周衡 policy precheck, per-relay snapshot/verify, prompt-rule insertion.

Python 3.9 compatible (macOS /usr/bin/python3). `precheck` must run under the python that
serves the live seats' buzz-team-thin (f66ef5e-preview venv, cb63521 wheel) so the profile is
generated by the same code: buzz_team.thin._load_policy + buzz_team.thin.command/_profile.

Process env is read with `ps -E` and reduced at once to a whitelist of keys; the raw output is
never stored or printed (it contains private keys).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys

HOME = Path(os.environ.get("HOME", "/Users/xupeng"))
LIVE_POLICIES = HOME / "lab/buzz/policies"
POLICY_NAME = "zhouheng-seatbelt.json"
OLD_SHA = "9e08735172c519e25a44c2ee92479a1fcedd9b031adfbd98c10336b005a13c23"
# Other 8 seats: Hogan baseline-before/policies-sha256.txt (2026-09-28 21:20:31 CST).
OTHER_BASELINE = {
    "fangwei-seatbelt.json": "af0cf59d0cafe925161618d43be369d17c9b5febff8c9e13b47a95b7cc7cf22d",
    "hanchuan-seatbelt.json": "9085ca476e62c3e529f4a2f07210e52802b2ab2eee034a6f76ca6b041c742e17",
    "lushen-seatbelt.json": "7125d513f55238a20a83c807025058be0cdb70bf50a3ca9f63e94717be5b8c68",
    "peizhao-seatbelt.json": "da6c411e556ac7d6f82967ea5baadf1b82ffb76fa2d5547ecb67d1dedbdbc5bf",
    "qinmu-seatbelt.json": "9bd3d3a3e50aa7e7fcc9427c440f22b739ced8a7e277fffc6cba41855d8ca5d6",
    "shenyu-seatbelt.json": "8bf475730ba1ded718808e9fadfa3630a0aa5941304400def5472b327b6e88c7",
    "suqing-seatbelt.json": "7086c4509877558b94b6ecc3deea0f85d8a62b72a32c08bfaf11136186332add",
    "weiping-seatbelt.json": "e2d35950dc7cdc3ea3d6f3aca2bada8cc41ed5c461b00dfc55ed31c41c57148e",
}
ZH_PUB = "51fb6cd8eb6a72674998d5be5b1e8e826e2d60c870337cffc3278225e4297d9e"
ZH_IDENTITY = HOME / ".local/share/buzz/agent-runtime/identities/a558771623f29898" / ZH_PUB
THIN_VENV = HOME / "lab/buzz/evidence/f66ef5e-preview/venv"
EXPECTED_AGENT_COMMAND = str(THIN_VENV / "bin/buzz-team-thin")
RELAYS = {"local": "ws://127.0.0.1:3000", "yuanbao": "wss://yuanbao.communities.buzz.xyz"}
LOCAL_PORT = 3000
PROXY_KEYS = ("HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy")
ACP_KEYS = ("BUZZ_RELAY_URL", "BUZZ_ACP_AGENT_COMMAND", "BUZZ_TEAM_POLICY_PATH", "KAIRO_PROVIDER", "GROK_HOME") + PROXY_KEYS
CHILD_KEYS = ("BUZZ_TEAM_POLICY_PATH", "GROK_HOME", "KAIRO_PROVIDER", "TMPDIR", "GROK_SANDBOX")
INVENTORY = HOME / "Library/Application Support/xyz.block.buzz.app/agents/managed-agents.json"
LOG_DIR = HOME / "Library/Application Support/xyz.block.buzz.app/agents/logs"
ZH_PERSONA = "zhufeng-pj"
SECTION = "## 长任务执行与恢复"
THIN_FAILURE = re.compile(r"buzz-team-thin: |must be an absolute path")


def sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


# ---------------------------------------------------------------- policy precheck (thin code)

def precheck(policy: Path, grok_home: Path, cwd: Path, profile_out: Path | None = None) -> dict:
    """Validate `policy` and render the Seatbelt profile with the running buzz_team.thin."""
    from buzz_team import thin  # the module the live launcher imports

    env = {"BUZZ_TEAM_POLICY_PATH": str(policy), "GROK_HOME": str(grok_home), "GROK_ACP_CWD": str(cwd)}
    policy_file, home, executable, roots = thin._load_policy(env)
    profile = thin._profile(roots)
    via = "thin._profile(roots) after thin._load_policy(env)"
    if thin.SEATBELT.is_file():
        argv, runtime_env, _ = thin.command(env, ["agent", "stdio"])
        if argv[:2] != [str(thin.SEATBELT), "-p"] or argv[2] != profile:
            raise ValueError("thin.command profile differs from thin._profile")
        via = "thin.command(env, ['agent','stdio'])[2] (== thin._profile(roots))"
        tmpdir = runtime_env["TMPDIR"]
    else:
        tmpdir = str(home.parent / "tmp") + "/"
    module = Path(thin.__file__)
    info = {"thin_module": str(module), "thin_py_sha256": sha256_file(module), "rendered_by": via,
            "python": sys.version.split()[0], "package": _package_origin(module),
            "policy": str(policy_file), "policy_sha256": sha256_file(policy_file),
            "policy_mode": oct(policy_file.stat().st_mode & 0o777), "grok_home": str(home),
            "grok_executable": str(executable), "roots": [str(r) for r in roots], "tmpdir": tmpdir,
            "profile_sha256": hashlib.sha256(profile.encode()).hexdigest()}
    write_paths = [Path(p) for p in json.loads(policy_file.read_text())["write_paths"]]
    for i, a in enumerate(write_paths):
        for b in write_paths[i + 1:]:
            if a == b or _relative(a, b) or _relative(b, a):
                raise ValueError(f"write paths overlap: {a} {b}")
    if profile_out:
        Path(profile_out).write_text(profile)
    return info


def _relative(a: Path, b: Path) -> bool:
    try:
        a.relative_to(b)
        return True
    except ValueError:
        return False


def _package_origin(module: Path) -> dict:
    site = module.parent.parent
    for dist in sorted(site.glob("buzz_team-*.dist-info")):
        out = {"dist_info": dist.name}
        direct = dist / "direct_url.json"
        if direct.is_file():
            data = json.loads(direct.read_text())
            out["url"] = data.get("url", "")
            match = re.search(r"/([0-9a-f]{40})/", out["url"])
            if match:
                out["package_sha"] = match.group(1)
        return out
    return {"dist_info": None}


# ---------------------------------------------------------------- processes

def _env_subset(text: str, keys) -> dict:
    found = {}
    for key in keys:
        match = re.search(r"(?:^|\s)" + re.escape(key) + r"=(\S*)", text)
        if match:
            found[key] = match.group(1)
    return found


def _run(argv) -> str:
    try:
        return subprocess.run(argv, capture_output=True, text=True, check=False).stdout
    except OSError:
        return ""


def list_processes(fixture: str | None = None) -> list:
    """buzz-acp processes with whitelisted env, TCP state and grok children."""
    if fixture:
        return json.loads(Path(fixture).read_text())
    procs = []
    for line in _run(["ps", "-axww", "-o", "pid=,ppid=,comm="]).splitlines():
        parts = line.split(None, 2)
        if len(parts) == 3 and parts[2].rsplit("/", 1)[-1] == "buzz-acp":
            procs.append(_describe(int(parts[0]), int(parts[1])))
    return sorted(procs, key=lambda p: p["pid"])


def _describe(pid: int, ppid: int) -> dict:
    env = _env_subset(_run(["ps", "-E", "-ww", "-o", "command=", "-p", str(pid)]), ACP_KEYS)
    tcp = [l.split(None, 8)[-1] for l in _run(["lsof", "-nP", "-a", "-p", str(pid), "-i", "TCP"]).splitlines()[1:]]
    children = []
    for c in _run(["pgrep", "-P", str(pid)]).split():
        children.append({"pid": int(c), "comm": _run(["ps", "-o", "comm=", "-p", c]).strip(),
                         "env": _env_subset(_run(["ps", "-E", "-ww", "-o", "command=", "-p", c]), CHILD_KEYS)})
    return {"pid": pid, "ppid": ppid, "lstart": _run(["ps", "-o", "lstart=", "-p", str(pid)]).strip(),
            "env": env, "tcp": tcp, "children": children}


def seat_of(proc: dict) -> str:
    policy = proc["env"].get("BUZZ_TEAM_POLICY_PATH", "")
    if policy:
        return Path(policy).name.replace("-seatbelt.json", "")
    home = proc["env"].get("GROK_HOME", "")
    return "zhouheng" if home == str(ZH_IDENTITY / "grok") else "?"


def relay_of(proc: dict) -> str:
    url = proc["env"].get("BUZZ_RELAY_URL", "").rstrip("/")
    for name, value in RELAYS.items():
        if url == value:
            return name
    return url or "?"


def is_zhouheng(proc: dict) -> bool:
    return proc["env"].get("GROK_HOME") == str(ZH_IDENTITY / "grok") or seat_of(proc) == "zhouheng"


def relay_state(proc: dict) -> str:
    if relay_of(proc) == "local":
        ok = any(f"->127.0.0.1:{LOCAL_PORT}" in t and "ESTABLISHED" in t for t in proc["tcp"])
        return "ESTABLISHED :3000" if ok else "NOT CONNECTED :3000"
    return "; ".join(proc["tcp"]) or "no TCP socket"


def policy_shas(policies: Path) -> dict:
    return {p.name: sha256_file(p) for p in sorted(Path(policies).glob("*.json"))}


def prompt_rows(inventory: Path, rule: str | None = None) -> list:
    rows = []
    try:
        data = json.loads(Path(inventory).read_text())
    except (OSError, ValueError):
        return rows
    for index, row in enumerate(data):
        if row.get("slug") == ZH_PERSONA or row.get("persona_id") == ZH_PERSONA:
            prompt = row.get("system_prompt") or ""
            rows.append({"index": index, "relay_url": row.get("relay_url") or "", "prompt_sha256":
                         hashlib.sha256(prompt.encode()).hexdigest(),
                         "rule_count": prompt.count(rule.strip()) if rule else None})
    return rows


def log_sizes() -> dict:
    return {p.name: p.stat().st_size for p in sorted(LOG_DIR.glob(ZH_PUB + "__*.log"))} if LOG_DIR.is_dir() else {}


def snapshot(policies: Path, inventory: Path, rule: str | None, fixture: str | None) -> dict:
    procs = list_processes(fixture)
    for p in procs:
        p["seat"], p["relay"], p["relay_state"] = seat_of(p), relay_of(p), relay_state(p)
    return {"fixture": bool(fixture), "processes": procs, "policies": policy_shas(policies),
            "zhouheng_prompt_rows": prompt_rows(inventory, rule), "zhouheng_logs": log_sizes()}


def print_snapshot(snap: dict) -> None:
    if snap["fixture"]:
        print("# TEST FIXTURE processes (not live)")
    print(f"# buzz-acp processes: {len(snap['processes'])}")
    print("relay\tseat\tpid\tlstart\tBUZZ_ACP_AGENT_COMMAND\tBUZZ_TEAM_POLICY_PATH\tKAIRO_PROVIDER\tproxies(6)\trelay_state\tgrok_children")
    for p in sorted(snap["processes"], key=lambda p: (p["relay"], p["seat"])):
        env = p["env"]
        proxies = ",".join(f"{k}={env.get(k, '<missing>')}" for k in PROXY_KEYS)
        kids = ",".join(str(c["pid"]) for c in p["children"]) or "-"
        print("\t".join([p["relay"], p["seat"], str(p["pid"]), p["lstart"], env.get("BUZZ_ACP_AGENT_COMMAND", "<missing>"),
                         env.get("BUZZ_TEAM_POLICY_PATH", "<missing>"), env.get("KAIRO_PROVIDER", "<missing>"),
                         proxies, p["relay_state"], kids]))
    for p in snap["processes"]:
        if is_zhouheng(p):
            for c in p["children"]:
                print(f"zhouheng child {p['relay']} {p['pid']}->{c['pid']} {c['comm']} " +
                      " ".join(f"{k}={c['env'].get(k, '<missing>')}" for k in CHILD_KEYS))
    print("# policy sha256")
    for name, digest in snap["policies"].items():
        print(f"{digest}  {name}")
    print("# 周衡 managed-agents rows")
    for row in snap["zhouheng_prompt_rows"]:
        print(f"row {row['index']} relay={row['relay_url'] or '<definition>'} system_prompt_sha256={row['prompt_sha256']} rule_count={row['rule_count']}")


# ---------------------------------------------------------------- verify

def verify(args) -> int:
    rule = Path(args.rule).read_text() if args.rule else None
    policies = Path(args.policies)
    expected_sha = args.old_sha if args.expect == "old" else sha256_file(Path(args.new_policy))
    baseline = json.loads(Path(args.baseline).read_text()) if args.baseline else OTHER_BASELINE
    policy_file = policies / POLICY_NAME
    fails = []

    def check(ok: bool, text: str) -> None:
        print(("PASS " if ok else "FAIL ") + text)
        if not ok:
            fails.append(text)

    print(f"issue57 verify: expect={args.expect} policies={policies} expected 周衡 sha256={expected_sha}")
    shas = policy_shas(policies)
    check(shas.get(POLICY_NAME) == expected_sha, f"{POLICY_NAME} sha256 {shas.get(POLICY_NAME)}")
    for name, digest in baseline.items():
        check(shas.get(name) == digest, f"{name} unchanged vs baseline-before ({shas.get(name, 'missing')[:12]})")
    check(len(shas) == 9, f"9 policy files present ({len(shas)})")
    if args.thin_python:
        pre = subprocess.run([args.thin_python, __file__, "precheck", "--policy", str(policy_file),
                              "--grok-home", str(ZH_IDENTITY / "grok"), "--cwd", str(ZH_IDENTITY / "workspace")],
                             capture_output=True, text=True)
        check(pre.returncode == 0, "thin._load_policy precheck " + (pre.stdout.strip().splitlines() or [pre.stderr.strip()])[-1][:160])

    if rule and args.prompt != "skip":
        want = 1 if args.prompt == "present" else 0
        rows = prompt_rows(Path(args.inventory), rule)
        check(len(rows) == 2, f"2 周衡 managed-agents rows in {args.inventory} ({[r['index'] for r in rows]})")
        for row in rows:
            check(row["rule_count"] == want, f"row {row['index']} prompt rule count {row['rule_count']} (want {want})")

    if not args.static_only:
        snap = snapshot(policies, Path(args.inventory), rule, args.ps_fixture)
        procs = snap["processes"]
        if snap["fixture"]:
            print("NOTE processes come from a TEST FIXTURE")
        check(len(procs) == 18, f"18 buzz-acp processes ({len(procs)})")
        for relay in RELAYS:
            mine = [p for p in procs if is_zhouheng(p) and relay_of(p) == relay]
            check(len(mine) == 1, f"[{relay}] exactly one 周衡 buzz-acp ({[p['pid'] for p in mine]})")
            for p in mine:
                env = p["env"]
                check(env.get("BUZZ_ACP_AGENT_COMMAND") == EXPECTED_AGENT_COMMAND,
                      f"[{relay}] pid {p['pid']} BUZZ_ACP_AGENT_COMMAND={env.get('BUZZ_ACP_AGENT_COMMAND', '<missing>')}")
                path = env.get("BUZZ_TEAM_POLICY_PATH")
                check(path == str(LIVE_POLICIES / POLICY_NAME), f"[{relay}] pid {p['pid']} BUZZ_TEAM_POLICY_PATH={path or '<missing>'}")
                digest = sha256_file(Path(path)) if path and Path(path).is_file() else "unreadable"
                check(digest == expected_sha, f"[{relay}] pid {p['pid']} policy-in-env sha256 {digest}")
                check(env.get("KAIRO_PROVIDER") == "grok", f"[{relay}] pid {p['pid']} KAIRO_PROVIDER={env.get('KAIRO_PROVIDER', '<missing>')}")
                for key in PROXY_KEYS:
                    check(env.get(key, "").endswith("127.0.0.1:9567"), f"[{relay}] pid {p['pid']} {key}={env.get(key, '<missing>')}")
                grok = [c for c in p["children"] if c["env"].get("GROK_SANDBOX") == "off"
                        and c["env"].get("TMPDIR") == str(ZH_IDENTITY / "tmp") + "/"]
                check(bool(grok), f"[{relay}] pid {p['pid']} grok child launched through thin (TMPDIR=identity tmp/, GROK_SANDBOX=off): {[c['pid'] for c in grok]}")
                state = relay_state(p)
                if relay == "local":
                    check(state.startswith("ESTABLISHED"), f"[local] pid {p['pid']} relay {state}")
                else:
                    print(f"INFO [{relay}] pid {p['pid']} relay state (recorded, not gated): {state}")
        if args.compare_state:
            before = json.loads(Path(args.compare_state).read_text())
            old = {(relay_of(p), seat_of(p)): p["pid"] for p in before["processes"]}
            new = {(relay_of(p), seat_of(p)): p["pid"] for p in procs}
            for key in sorted(set(old) | set(new)):
                if key[1] == "zhouheng":
                    if args.restarted:
                        check(new.get(key) not in (None, old.get(key)), f"[{key[0]}] 周衡 new pid {old.get(key)} -> {new.get(key)}")
                    else:
                        check(new.get(key) == old.get(key), f"[{key[0]}] 周衡 pid unchanged {old.get(key)} -> {new.get(key)}")
                else:
                    check(new.get(key) == old.get(key), f"[{key[0]}] {key[1]} pid unchanged {old.get(key)} -> {new.get(key)}")
            sizes = before.get("zhouheng_logs", {})
            for name, size in log_sizes().items():
                with open(LOG_DIR / name, "rb") as handle:
                    handle.seek(sizes.get(name, 0))
                    tail = handle.read().decode("utf-8", "replace")
                bad = [l for l in tail.splitlines() if THIN_FAILURE.search(l)]
                check(not bad, f"log {name[:12]}…{name[-12:]} has no thin launch failure since snapshot"
                      + (f": {bad[-1][:160]} -> STOP, rollback, report to Jenny" if bad else ""))
    print("VERIFY PASS" if not fails else f"VERIFY FAIL ({len(fails)})")
    return 0 if not fails else 1


# ---------------------------------------------------------------- prompt rule

def insert_rule(prompt: str, rule: str) -> str:
    """Append `rule` as the last line of the last '## 长任务执行与恢复' section."""
    line = rule.strip()
    if line in prompt:
        raise ValueError("rule already present")
    lines = prompt.split("\n")
    starts = [i for i, text in enumerate(lines) if text.startswith(SECTION)]
    if not starts:
        raise ValueError("section not found: " + SECTION)
    end = len(lines)
    for i in range(starts[-1] + 1, len(lines)):
        if lines[i].startswith("#"):
            end = i
            break
    last = max(i for i in range(starts[-1], end) if lines[i].strip())
    return "\n".join(lines[:last + 1] + [line] + lines[last + 1:])


def insert_inventory(inventory: Path, rule: str) -> list:
    data = json.loads(inventory.read_text())
    touched = []
    for index, row in enumerate(data):
        if row.get("slug") == ZH_PERSONA or row.get("persona_id") == ZH_PERSONA:
            row["system_prompt"] = insert_rule(row.get("system_prompt") or "", rule)
            touched.append(index)
    if len(touched) != 2:
        raise ValueError(f"expected 2 周衡 rows, found {touched}")
    tmp = inventory.with_name(inventory.name + ".issue57-new")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2))
    os.chmod(tmp, inventory.stat().st_mode & 0o777)
    tmp.replace(inventory)
    return touched


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="issue57")
    sub = parser.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("precheck")
    p.add_argument("--policy", required=True)
    p.add_argument("--grok-home", default=str(ZH_IDENTITY / "grok"))
    p.add_argument("--cwd", default=str(ZH_IDENTITY / "workspace"))
    p.add_argument("--profile-out")
    p.add_argument("--json-out")
    s = sub.add_parser("snapshot")
    s.add_argument("--policies", default=str(LIVE_POLICIES))
    s.add_argument("--inventory", default=str(INVENTORY))
    s.add_argument("--rule")
    s.add_argument("--ps-fixture", default=os.environ.get("ISSUE57_TEST_PS_FIXTURE"))
    s.add_argument("--out")
    v = sub.add_parser("verify")
    v.add_argument("--expect", choices=("old", "new"), required=True)
    v.add_argument("--policies", default=str(LIVE_POLICIES))
    v.add_argument("--new-policy", default=str(Path(__file__).with_name(POLICY_NAME)))
    v.add_argument("--inventory", default=str(INVENTORY))
    v.add_argument("--rule")
    v.add_argument("--prompt", choices=("present", "absent", "skip"), default="skip")
    v.add_argument("--thin-python")
    v.add_argument("--static-only", action="store_true")
    v.add_argument("--old-sha", default=OLD_SHA)
    v.add_argument("--baseline", help="JSON {name: sha256} for the other 8 policies (default: baseline-before)")
    v.add_argument("--compare-state")
    v.add_argument("--restarted", action="store_true")
    v.add_argument("--ps-fixture", default=os.environ.get("ISSUE57_TEST_PS_FIXTURE"))
    i = sub.add_parser("insert-rule")
    i.add_argument("--inventory", required=True)
    i.add_argument("--rule", required=True)
    args = parser.parse_args(argv)
    try:
        if args.cmd == "precheck":
            info = precheck(Path(args.policy), Path(args.grok_home), Path(args.cwd),
                            Path(args.profile_out) if args.profile_out else None)
            text = json.dumps(info, ensure_ascii=False, indent=2)
            if args.json_out:
                Path(args.json_out).write_text(text + "\n")
            print(text)
            print(f"PRECHECK PASS policy_sha256={info['policy_sha256']} profile_sha256={info['profile_sha256']}")
            return 0
        if args.cmd == "snapshot":
            rule = Path(args.rule).read_text() if args.rule else None
            snap = snapshot(Path(args.policies), Path(args.inventory), rule, args.ps_fixture)
            if args.out:
                Path(args.out).write_text(json.dumps(snap, ensure_ascii=False, indent=2) + "\n")
            print_snapshot(snap)
            return 0
        if args.cmd == "verify":
            return verify(args)
        if args.cmd == "insert-rule":
            rows = insert_inventory(Path(args.inventory), Path(args.rule).read_text())
            print(f"issue57: rule inserted into managed-agents rows {rows}")
            return 0
    except (OSError, ValueError, KeyError) as exc:
        print(f"issue57 {args.cmd}: FAIL {exc}", file=sys.stderr)
        return 1
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
